In [1]:
#numpy practice code
import numpy as np

In [2]:
myarr=np.array([1,2,3,4])
myarr


array([1, 2, 3, 4])

In [3]:
myarr1=np.array([1,2,3777,4],np.int64)
myarr1
#int8,int32,int64 can also be used (all are datatypes)


array([   1,    2, 3777,    4], dtype=int64)

In [4]:
myarr2=np.array([1,2,33,44]) #one dimensional arrays
myarr2[0]

1

In [5]:
myarr3=np.array([[1,2,55,66,44]]) #two dimensional array
myarr3[0][0]

1

In [6]:
myarr3.shape 
#used to get information regarding array column and rows 
#myarr3 has 1 row and 5 columns

(1, 5)

In [7]:
myarr3.dtype #to find the datatype of array

dtype('int32')

In [8]:
myarr3[0,1]=45 #assigning values to the array indexes
myarr3

array([[ 1, 45, 55, 66, 44]])

In [9]:
#numpy array creation methods
#conversion from other python structures
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({1,22,33,54,44})
#from dictionary avoid dtype as object when doing calculation tasks

array({1, 33, 22, 54, 44}, dtype=object)

In [14]:
zeros=np.zeros((2,5)) #to create an array having 2 rows and 5 columns and fill it with zeros
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng=np.arange(15) #to create a single dimensional array with range of 0-14
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
lspace=np.linspace(1,4,4) #to create an array which is having first element as 1 and last element as 4 and number elements are 4 
lspace #difference between all 4 elements is same

array([1., 2., 3., 4.])

In [17]:
emp=np.empty((4,2)) #to create an array and fill it with random numbers 
emp

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.24610994e-306],
       [1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 2.29178686e-312]])

In [18]:
emp1=np.empty_like(lspace) #to create another array having same dimensions as other array you entered (in this case lspace)
emp1

array([1., 2., 3., 4.])

In [19]:
#to create an identity matrix
ide=np.identity(45)
ide


array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [20]:
ide.shape

(45, 45)

In [21]:
arr8=np.arange(99)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr8.reshape(3,33) #3x33=99 to reshape the array
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
arr8=arr8.reshape(3,33) #to upgrade the shape of array
arr8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [24]:
arr8.shape

(3, 33)

In [25]:
arr8=arr8.ravel() #to transform a two dimensional array into a 1 dimensional array

In [26]:
arr8.shape

(99,)

In [27]:
x=[[11,12,13],[14,15,16],[17,18,19]]
arr9=np.array(x)
arr9.sum(axis=0) #axis=0 means row 42=11+14+17





array([42, 45, 48])

In [28]:
arr9.sum(axis=1) #axis=1 means column 36=11+12+13


array([36, 45, 54])

In [29]:

arr9

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [30]:
arr9.T #Transpose of matrix 


array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [31]:
arr9.flat

In [32]:
for i in arr9.flat: #in order to iterate through whole array
    print(i)

11
12
13
14
15
16
17
18
19


In [33]:
arr9.ndim #to tell the number of dimensions of array

2

In [34]:
arr9.size #to get size of array

9

In [35]:
arr9.nbytes #to know the total  number of bytes consumed/used by the array

36

In [36]:
one=np.array([1,2,3,4,55,33,99])
one.argmax() #gives the index where largest element


6

In [43]:
g=one.argmin() #gives the index of smallest element
g

0

In [44]:
one.argsort() #gives the sorted indexes of elements of an array

array([0, 1, 2, 3, 5, 4, 6], dtype=int64)

In [46]:
arr10=np.array([[1,2,3],[4,5,6]]) #minimum element in 2-D array is found by making the 2D array linear 
arr10.argmin() #it then finds the index of the smallest element
arr10.argmax() #same with argmax()


5

In [47]:
arr10.argmax(axis=0)
#with rows it will compare as in arr10 4,5,6 are largest elements of their rows and indexes are 1,1,1

array([1, 1, 1], dtype=int64)

In [48]:
arr10.argmax(axis=1)
#axis=1

array([2, 2], dtype=int64)

In [49]:
arr10.argsort(axis=0)


array([[0, 0, 0],
       [1, 1, 1]], dtype=int64)

In [50]:
arr10.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [52]:
arr11=np.array([[1,2,3],[1,2,3]])
arr12=np.array([[1,1,1],[1,1,1]])
arr11+arr12 #adding two arrays 

array([[2, 3, 4],
       [2, 3, 4]])

In [53]:
[12,13]+[14,15] #concatenating two lists


[12, 13, 14, 15]

In [54]:
arr11*arr12 #multiplying two arrays

array([[1, 2, 3],
       [1, 2, 3]])

In [55]:
np.sqrt(arr11) #taking square root of an array

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [56]:
arr11.sum() #sum of all elements in an array

12

In [57]:
arr11.max() #prints maximum value of an array

3

In [58]:
arr11.min() #prints minimum value of an array

1

In [61]:
np.where(arr11<3) #[0,0],[0,1],[1,0],[1,1]

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [62]:
np.count_nonzero(arr11) #gives count of non zero elements

6

In [63]:
np.nonzero(arr11) #gives indexes of non zero elements [0,0],[0,1],[0,2],[1,0],[1,1],[1,2]

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [66]:
import sys
py_arr=[10,12,14,15]
arr13=np.array(py_arr)
sys.getsizeof(1)*len(py_arr) #size of normal array without using numpy



112

In [68]:
arr13.itemsize*arr13.size #size of same  array after using numpy

16

In [ ]:
#link for numpy array attributes and methods
#https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html